FileUpDownLoad/Models/Person.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace FileUpDownLoad.Models
{
    public class Person
    {
        public int ID { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }
        [Required]
        [StringLength(50, ErrorMessage = "First name cannot be longer than 50 characters.")]
        [Column("FirstName")]
        [Display(Name = "First Name")]
        public string FirstMidName { get; set; }

        [Display(Name = "Full Name")]
        public string FullName
        {
            get
            {
                return LastName + ", " + FirstMidName;
            }
        }
        public virtual ICollection<File> Files { get; set; }
        public virtual ICollection<FilePath> FilePaths { get; set; }
    }
}

FileUpDownLoad/Controllers/PersonController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FileUpDownLoad.Models;
using System.IO;
using System.Data.Entity.Infrastructure;

namespace FileUpDownLoad.Controllers
{
    public class PersonController : Controller
    {
        private UploadDownloadContext db = new UploadDownloadContext();

        // GET: Person
        public ActionResult Index()
        {
            return View(db.People.ToList());
        }

        // GET: Person/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.People.Include(p=>p.Files).Include(f=>f.FilePaths).FirstOrDefault(p=>p.ID == id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        // GET: Person/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Person/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,LastName,FirstMidName")] Person person, 
            HttpPostedFileBase upload, HttpPostedFileBase uploadfs, HttpPostedFileBase[] files)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var uploadAvatar = upload;
                    var uploadPhoto = uploadfs;

                    // Avatar
                    if (uploadAvatar != null 
                        &&
                        uploadAvatar.ContentLength > 0 
                        && 
                        (uploadAvatar.ContentType.ToLower() == "image/jpeg" || uploadAvatar.ContentType.ToLower() == "image/png"))
                    {
                        var avatar = new FileUpDownLoad.Models.File
                        {
                            FileName = Path.GetFileName(upload.FileName),
                            FileType = FileType.Avatar,
                            ContentType = upload.ContentType
                        };
                        using (var reader = new BinaryReader(upload.InputStream))
                        {
                            avatar.Content = reader.ReadBytes(upload.ContentLength);
                        }
                        person.Files = new List<Models.File> { avatar };
                    }


                    // Photo
                    if (uploadPhoto != null
                        &&
                        uploadPhoto.ContentLength > 0
                        &&
                        (uploadPhoto.ContentType.ToLower() == "image/jpeg" || uploadPhoto.ContentType.ToLower() == "image/png"))
                    {
                        var guid = Guid.NewGuid().ToString();
                        var fileName = guid + Path.GetExtension(uploadPhoto.FileName);
                        var photo = new FilePath
                        {
                            //FileName = System.IO.Path.GetFileName(uploadPhoto.FileName),
                            /*FileName = Guid.NewGuid().ToString() + Path.GetExtension(uploadPhoto.FileName)*/
                            FileName = fileName,
                            FileType = FileType.Photo,
                        };
                        var path = Path.Combine(Server.MapPath("~/Content/Images"), fileName);
                        person.FilePaths = new List<FilePath>();
                        person.FilePaths.Add(photo);
                        uploadPhoto.SaveAs(path);
                    }

                    // Documents
                    if (files.Count() != 0)
                    {

                        //iterating through multiple file collection   
                        foreach (HttpPostedFileBase file in files)
                        {
                            //Checking file is available to save.  
                            if (file != null && file.ContentLength > 0)
                            {
                                string fileName = Path.GetFileName(file.FileName);
                                string fileType = file.ContentType;
                                int fileSize = file.ContentLength;
                                var document = new FilePath
                                {
                                    FileName = fileName,
                                    FileType = FileType.Document,
                                    ContentType = fileType,
                                    ContentSize = fileSize
                                };
                                
                                // giving a file system path
                                var path = Path.Combine(Server.MapPath("~/App_Data"), fileName);
                                //instantiating list of filepath
                                person.FilePaths = new List<FilePath>();
                                // Adding document in context
                                person.FilePaths.Add(document);
                                //Save file to server folder  
                                file.SaveAs(path);
                                ////assigning file uploaded status to ViewBag for showing message to user.  
                                //ViewBag.UploadStatus = files.Count().ToString() + " files uploaded successfully.";
                            }
                        }
                    }
                    db.People.Add(person);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

            }
            catch (RetryLimitExceededException /*dex*/)
            {
                // Log the error (uncomment dex varial name and add a line here to write a log)
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }
           

            return View(person);
        }

        // GET: Person/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.People.Include(f => f.Files).SingleOrDefault(f => f.ID == id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        // POST: Person/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,LastName,FirstMidName")] Person person, HttpPostedFileBase upload, HttpPostedFileBase uploadfs)
        {
            if (ModelState.IsValid)
            {
                var personToUpdate = db.People.Find(person.ID);
                var uploadAvatar = upload;
                var uploadPhoto = uploadfs;
                try
                {

                    //Avatar
                    if (uploadAvatar != null
                        &&
                        uploadAvatar.ContentLength > 0
                        &&
                        (uploadAvatar.ContentType.ToLower() == "image/jpeg" || uploadAvatar.ContentType.ToLower() == "image/png"))
                    {
                        
                        if (personToUpdate.Files.Any(f => f.FileType == FileType.Avatar))
                        {
                            db.Files.Remove(personToUpdate.Files.First(f => f.FileType == FileType.Avatar));
                        }
                        var avatar = new Models.File
                        {
                            FileName = Path.GetFileName(uploadAvatar.FileName),
                            FileType = FileType.Avatar,
                            ContentType = uploadAvatar.ContentType
                        };
                        using (var reader = new BinaryReader(uploadAvatar.InputStream))
                        {
                            avatar.Content = reader.ReadBytes(uploadAvatar.ContentLength);
                        }
                        personToUpdate.Files = new List<Models.File> { avatar };
                    }


                    // Photo
                    //if (uploadPhoto != null && uploadPhoto.ContentLength > 0)
                    //{
                    //    var photo = new FilePath
                    //    {
                    //        FileName = System.IO.Path.GetFileName(uploadPhoto.FileName),
                    //        FileType = FileType.Photo
                    //    };
                    //    personToUpdate.FilePaths = new List<FilePath>();
                    //    personToUpdate.FilePaths.Add(photo);
                    //}
                }
                catch (RetryLimitExceededException /*dex*/)
                {
                    // Log the error
                    ModelState.AddModelError("", "Unable to save changes. Try again.");
                }
                db.Entry(personToUpdate).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(person);
        }

        #region way1
        //[HttpPost, ActionName("Edit")]
        //[ValidateAntiForgeryToken]
        //public ActionResult EditPost(int? id, HttpPostedFileBase upload)
        //{
        //    if (id == null)
        //    {

FileUpDownLoad/Views/Person/Create.cshtml
@model FileUpDownLoad.Models.Person

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Person", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Person</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstMidName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstMidName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstMidName, "", new { @class = "text-danger" })
            </div>
        </div>

        @*image on database*@
        <div class="form-group">
            @Html.Label("Avatar", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="Avatar" name="upload" />
            </div>
        </div>

        @*image on file system*@
        <div class="form-group">
            @Html.Label("Photo", new { @class = "control-label col-md-2"})
            <div class="col-md-10">
                <input type="file" id="photo" name="uploadfs" />
            </div>
        </div>
        @*multiple input files enabled HTML5*@
        <div class="form-group">
            @Html.Label("Documents", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="document" name="files" multiple />
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FileUpDownLoad/Views/Person/Delete.cshtml
@model FileUpDownLoad.Models.Person

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Person</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstMidName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstMidName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FileUpDownLoad/Views/Person/Details.cshtml
@model FileUpDownLoad.Models.Person

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Person</h4>
    <hr />
    <dl class="dl-horizontal">
        @if (Model.Files.Any(f => f.FileType == FileType.Avatar))
        {
            @*<dt>Avtar</dt>
                <dd>
                    <img class="img img-responsive img-thumbnail" src="~/File?id=@Model.Files.First(f => f.FileType == FileType.Avatar).FileId" height="100px" width="100px" alt = "avatar" />
                </dd>*@
            <dt>
                <img class="img img-responsive img-thumbnail" src="~/File?id=@Model.Files.First(f => f.FileType == FileType.Avatar).FileId" height="100px" width="100px" alt="avatar" />
            </dt>
            <shadow></shadow>
            <dd>
                @Html.DisplayFor(model => model.FirstMidName) @Html.DisplayFor(model => model.LastName)
            </dd>

        }
        else
        {
            <dt class="img img-thumbnail"> image </dt>
            <shadow></shadow>
            <dd>
                @Html.DisplayFor(model => model.FirstMidName) @Html.DisplayFor(model => model.LastName)
            </dd>

        }
       
       


        @*<dt>
                @Html.DisplayNameFor(model => model.LastName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LastName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.FirstMidName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FirstMidName)
            </dd>*@

    </dl>

    <div class="row">
        
        @if (Model.FilePaths.Any(f => f.FileType == FileType.Photo))
        {
            <h3>Photo</h3>
            foreach (var path in Model.FilePaths)
            {
                <div class="col-md-4">
                    <p> This is the photo uploaded by you.</p>
                    <img class="img-responsive img-thumbnail" height="200px" width="auto" src="~/Content/Images/@path.FileName" />
                </div>
                
             }
         }
    </div>

</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FileUpDownLoad/Views/Person/Edit.cshtml
@model FileUpDownLoad.Models.Person

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Person", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Person</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstMidName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstMidName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstMidName, "", new { @class = "text-danger" })
            </div>
        </div>

        @if (Model.Files.Any(f => f.FileType == FileType.Avatar))
        {
            <div class="form-group">
                <span class="control-label col-md-2">
                    <strong>Current Avatar</strong>
                </span>
                <div class="col-md-10">
                    <img class="img-responsive img-thumbnail" height="200px" width="200px"  src="~/File?id=@Model.Files.First(f=>f.FileType == FileType.Avatar).FileId" alt="avatar" />
                </div>
            </div>
        }

        <div class="form-group">
           @Html.Label("Avatar", new { @class = "control-label col-md-2"})
            <div class="col-md-10">
                <input type="file" id="Avatar" name="upload" />
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save Change" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FileUpDownLoad/Views/Person/Index.cshtml
@model IEnumerable<FileUpDownLoad.Models.Person>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstMidName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FirstMidName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>